### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by julian-ao** [appKom/home#21]
![image](https://github.com/user-attachments/assets/cd0bbc1a-0331-4d33-9e5a-84acfbf41b3d)

Get this as response:
```
{
    "error": "Internal server error",
    "message": "Could not load credentials from any providers"
}
```

**Comment by fredrir** [comment]
![image](https://github.com/user-attachments/assets/390dff8a-a9ae-447b-9202-2cb517418186)

Funker for meg. Fyllte du ut alle fieldsene?

**Comment by fredrir** [comment]
Eller vent, funker kun i localhost, ikke i prod

**Comment by fredrir** [comment]
Lol, manglet en .env variabel i Vercel. Skal være fikset nå🙏
