### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by fredrir** [appKom/home#5]
The current color template and design is kinda ugly

**Comment by julian-ao** [comment]
tips for design. sjekk ut https://v0.dev/. funker som chatgpt, bare dritgod på design, kan også de live resultatet av koden den gir deg. @fredrir

**Comment by fredrir** [comment]
> tips for design. sjekk ut https://v0.dev/. funker som chatgpt, bare dritgod på design, kan også de live resultatet av koden den gir deg. @fredrir 

Ooof skal sjekke det ut🔥🔥
